name: Deploy Laravel via Docker

# Jalankan otomatis setiap kali push ke branch 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to VPS and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # 1. Masuk ke direktori proyek di VPS (Ganti sesuai direktori Anda)
            cd /home/ubuntu/kref-barber

            # 2. Tarik update kode terbaru
            git pull origin main

            # 3. Build & jalankan Docker Container
            docker compose up -d --build
